### PR TITLE
Sphinx Documentation addition

### PR DESCRIPTION
**Pull request by Raistlfiren**
There is still a lot to do in regards to documenting. I think this is a good start to at least generate some simple Sphinx documentation for the API and code base. The convenient thing about Sphinx is that we can have documentation on the whole code base instead of just the API. Plus we can include it in the code, so we aren't really maintaining much of an external file for it. The API still has a long way to go, and it might be better if we get more of it done before we have API specific documentation. Hopefully, this will allow people to pick the API up easier than before.

### CODE REVIEW

**Comment by Sheeo** [comment]
Hey, sorry for the late reply on this. I'm lacking documentation on how to build the documentation :)

**Comment by Raistlfiren** [comment]
lol... Whoops, I didn't document how to get the documentation up and running! I do have a requirements.txt in the docs/ that includes all of those. I thought I also had a script to automatically install the requirements and make the documentation, but I must of not included it in any commits. I will update the README with a short blurb on setting up the documentation, and include a script to automatically compile it. Thanks for going through this :)

**Comment by Sheeo** [comment]
Great, thanks :) Nice work with the rest!

**Comment by Raistlfiren** [comment]
@Sheeo Bump :)

**Comment by IDragonfire** [comment]
+1 
Can you solve the merge conflicts?

**Comment by Raistlfiren** [comment]
I am not sure if I screwed this up even more or not! lol

**Comment by IDragonfire** [comment]
Ths diff looks a little bit big:
https://github.com/FAForever/api/pull/28/files

**Comment by IDragonfire** [comment]
@Raistlfiren
I rebased your branch from 8901440 onto develop ..

https://github.com/FAForever/api/compare/pr/28?expand=1
https://github.com/FAForever/api/tree/pr/28

Can you test this branch?
Specially this files

* api/games.py
* .gitignore
*

**Comment by Raistlfiren** [comment]
Thank you @IDragonfire, I am looking into this now.

**Comment by Raistlfiren** [comment]
Thanks, I am closing this one and creating a new PR. https://github.com/FAForever/api/pull/47

I updated the gitignore file.

**Pull request closed without merging**
