### PR TITLE
Updated Documentation

### PR DESCRIPTION
**Pull request by Raistlfiren**
Added information about the config.example.py in the documentation

### CODE REVIEW

**Comment by IDragonfire** [comment]
Or use environment variables

**Comment by Raistlfiren** [comment]
Yeah, but environment variables are never used in the setup to get the docker instance up and running.

**Comment by IDragonfire** [comment]
Environment variables are used here https://github.com/FAForever/api/blob/develop/config.example.py

Maybe I will add a tutorial in the Future...

**Comment by Raistlfiren** [comment]
How I see it, you either need to modify the config.yml with the correct database settings manually OR just add the password to the config.yml by default and go from there.

**Comment by IDragonfire** [comment]
Or use environment variables... 
I described it here 
https://github.com/FAForever/server/blob/develop/README.md

**Pull request closed without merging**
