### PR TITLE
Add clan tag colour to fetched data

### PR DESCRIPTION
**Pull request by HardlySoftly**

### CODE REVIEW

**Comment by HardlySoftly** [comment]
See https://github.com/FAForever/db/pull/31 and https://github.com/FAForever/faftools/pull/20

**Comment by HardlySoftly** [comment]
The api change needs the two PRs I linked above in order to work

**Comment by HardlySoftly** [comment]
ok I'm back from holiday now, so this PR can officially go ahead again

**Comment by HardlySoftly** [comment]
Still waiting

**Comment by HardlySoftly** [comment]
The sooner there is API support, the sooner client support can be added.

**Comment by Sheeo** [comment]
I don't see the PR for the client?

**Comment by HardlySoftly** [comment]
There is no new PR for the client yet

**Comment by Sheeo** [comment]
Let me know when it's ready and we'll review the three pr's in succession.

**Comment by HardlySoftly** [comment]
What three PRs?  The DB and faftools PRs have already gone through.  I can't see any reason for the API to not be reporting all the data it has available to it for each clan.

**Comment by HardlySoftly** [comment]
Why is a client PR required to change the API?

**Comment by micheljung** [comment]
Can you point the DB to latest develop?

**Comment by micheljung** [comment]
You need to update the DB submodule one more time, and add unit tests, then this should be good to be merged.

**Pull request closed without merging**
