### PR TITLE
Feature/deployment

### PR DESCRIPTION
**Pull request by aeoncleanse**
Depends on https://github.com/FAForever/faftools/pull/23

### CODE REVIEW

**Comment by micheljung** [comment]
Didn't we agree to not make an UI? :P

**Comment by aeoncleanse** [comment]
No... We agreed TO create one, eventually, I thought. Then it turned out to be simpler than I expected.

**Comment by micheljung** [comment]
At first, then we (or at least I :P) realized that it's easier if we do deployment by branch

**Comment by aeoncleanse** [comment]
Yup. This does that.

**Comment by Brutus5000** [comment]
obsolete, please see #143

**Pull request closed without merging**
